@baseUrl = http://157.173.110.195:8089/index.php
@cnpj = 06013812000158

### NFSe - Ferramentas - OpenSSL info
GET {{baseUrl}}/nfse/ferramentas/openssl-info
Accept: application/ld+json

### NFSe - Ferramentas - Obter certificados
GET {{baseUrl}}/nfse/ferramentas/obter-certificados
Accept: application/ld+json

### NFSe - Padrao nacional - consultar DPS por chave
### Substituir a chave por uma chave valida de DPS.
GET {{baseUrl}}/nfse/padrao-nacional/consultar-dps-por-chave?AChaveDPS=SUBSTITUIR_CHAVE_DPS
Accept: application/ld+json

### NFSe - Padrao nacional - consultar NFSe por chave
### Substituir a chave por uma chave valida de NFSe.
GET {{baseUrl}}/nfse/padrao-nacional/consultar-nfse-por-chave?AChaveNFSe=SUBSTITUIR_CHAVE_NFSE
Accept: application/ld+json

### NFSe - Demais provedores - consultar situacao
### Substituir os campos conforme o provedor usado.
GET {{baseUrl}}/nfse/demais-provedores/consultas/consultar-situacao?AProtocolo=SUBSTITUIR_PROTOCOLO&ANumLote=1
Accept: application/ld+json

### NFSe - Demais provedores - consultar NFSe por periodo
### Substituir as datas conforme o teste.
GET {{baseUrl}}/nfse/demais-provedores/consultas/consultar-nfse-por-periodo?ADataInicial=01/04/2026&ADataFinal=30/04/2026&APagina=1&ATipoPeriodo=1
Accept: application/ld+json

### NFSe - Demais provedores - consultar NFSe por faixa
GET {{baseUrl}}/nfse/demais-provedores/consultas/consultar-nfse-por-faixa?ANumeroInicial=1000&ANumeroFinal=1010&APagina=1
Accept: application/ld+json

### NFSe - Demais provedores - link NFSe
GET {{baseUrl}}/nfse/demais-provedores/envio/link-nfse?ANumeroNFSe=12345&ACodigoVerificacao=ABC12345&AValorServico=150.00
Accept: application/ld+json

### NFSe - Demais provedores - gerar token
GET {{baseUrl}}/nfse/demais-provedores/envio/gerar-token
Accept: application/ld+json

### NFSe - Servicos prestados por periodo
GET {{baseUrl}}/nfse/demais-provedores/servicos-prestados/por-periodo?ADataInicial=01/04/2026&ADataFinal=30/04/2026&APagina=1&ATipoPeriodo=1
Accept: application/ld+json

### NFSe - Servicos tomados por numero
GET {{baseUrl}}/nfse/demais-provedores/servicos-tomados/por-numero?ANumero=12345&APagina=1&ADataInicial=01/04/2026&ADataFinal=30/04/2026&ATipoPeriodo=1
Accept: application/ld+json
